### ISSUE TITLE
dodawanie grafik w aktualnościach

### ISSUE THREAD

**Issue by kbasia** [fnp/cybernauci#10]
Po próbie wgrania grafiki pojawia się komunikat: Nie można utworzyć katalogu &#8222;wp-content/uploads/2016/04&#8221;. Czy WordPress ma uprawnienie do zapisu do katalogu nadrzędnego?

**Comment by Cain-Ish** [comment]
@danielmacyszyn trzeba ograć te prawa zapisu na serwerze. Tworzenie linków to jedno ale również nie da sie wgrywac z poziomu wordpressa rzeczy.

**Comment by danielmacyszyn** [comment]
@Cain-Ish w którym folderze te rzeczy powinny się zapisywać? Nie widzę w ogóle folderu wp-content/uploads. Zmieniłem uprawnienia do całego wp-content. Pls sprawdź czy teraz jest OK.
