### ISSUE TITLE
przesłane formularze

### ISSUE THREAD

**Issue by kbasia** [fnp/cybernauci#13]
Dokąd trafiają?
Nie mogę ich znaleźć tutaj:
http://cybernauci.edu.pl/wp-admin/edit.php?post_status=all&post_type=nf_sub&m=0&form_id&begin_date=01%2F04%2F2016&end_date=12%2F04%2F2016&filter_action=Przefiltruj&orderby=id&order=desc

nie dostajemy też informacji, że ktoś zarejstrował szkołę

**Comment by Cain-Ish** [comment]
Z górnego musisz wybrać "Add school" (http://cybernauci.edu.pl/wp-admin/edit.php?post_status=all&post_type=nf_sub&m=0&form_id=6&begin_date=01%2F04%2F2016&end_date=12%2F04%2F2016&paged=1)

Mail jest ustawiony(na razie mój ale nie wychodzi nic - możliwe ze to kwestia ustawien wysyłki maili z serwera albo uprawnień - tak czy owak prawdopodobnie @danielmacyszyn ci pomoże). Ustawienia na jaki mail idzie ustawia się w "New school added" (http://cybernauci.edu.pl/wp-admin/admin.php?page=ninja-forms&tab=notifications&form_id=6)

**Comment by kbasia** [comment]
Ok, dzięki,

tu ["New school added" (http://cybernauci.edu.pl/wp-admin/admin.php?page=ninja-forms&tab=notifications&form_id=6)] jest ustawione, że mają spływać na nasz (cybernauci@nowoczesnapolska.org.pl) adres,
możemy to sprawdzić?

**Comment by Cain-Ish** [comment]
Nie wiem na jaki miały spływać wiec wpisałem tamten. Możecie to zmienić. Wysyłanie email jest stawiany (https://github.com/fnp/cybernauci/issues/4)

**Comment by kbasia** [comment]
ten jest ok - bardziej chodziło mi o to, że nie spływają, ale rozumiem, że to zależy od tego silnika pocztowego, o którym pisałeś

**Comment by Cain-Ish** [comment]
Tak - kwestia tylko uruchomienia tego przez @danielmacyszyn
