### ISSUE TITLE
dodanie strony cybernauci.edu.pl do PIWIKa

### ISSUE THREAD

**Issue by kbasia** [fnp/cybernauci#14]
Potrzebujemy tego, żeby móc zbierać statystyki

**Comment by danielmacyszyn** [comment]
@Cain-Ish 
Kod do wstawienia:
http://pastebin.com/Ln2pNbY1

**Comment by kbasia** [comment]
a czy mogę jesze prosić o udostępnienie mi tych statystyk?
jestem na piwiku jako barbararywoszejew
