### ISSUE TITLE
jak zmienić linki zakładek

### ISSUE THREAD

**Issue by kbasia** [fnp/cybernauci#22]
czy możemy samodzielnie ustawiać linki dla kolejnych zakłade/wpisów?
bo teraz np. do formularza mamy taki:
http://cybernauci.edu.pl/?page_id=7
lepszy byłby http://cybernauci.edu.pl/zglos-szkole
próbowałam tutaj:
http://cybernauci.edu.pl/wp-admin/options-permalink.php
ale wtedy wszystko zniknęło...

**Comment by Cain-Ish** [comment]
@kbasia @paulinaoltusek Permalinks ustawia sie właśnie w opcjach ale serwer musi pozwolić na zmiany redirect. Wczesniej @danielmacyszyn z tym walczył i z tego co wiem to naprawił to wiec trzeba sprawdzić czy działa, a jeśli nie to dlaczego. Sama zmiana uprawnień powinna była to naprawić

**Comment by kbasia** [comment]
działa. zamykam

**Comment by kbasia** [comment]
jednak nie,
jak zamieniłam przy formularzu na zglos-szkole,
to wszystkie aktualności nas do formularza przenosiły,
jeszcze w tym pogrzebię i zobaczę, czy mogę sama, czy potrzebujemy pomocy.

**Comment by janek37** [comment]
Ustawiłem „Nazwa wpisu” w http://cybernauci.edu.pl/wp-admin/options-permalink.php i chyba jest to, o co chodzi?

**Comment by kbasia** [comment]
super!
zamykam!

b.

W dniu 2016-05-20 11:21, janek37 napisał(a):

> Ustawiłem „Nazwa wpisu” w
> http://cybernauci.edu.pl/wp-admin/options-permalink.php i chyba jest
> to, o co chodzi?
> 
> ## 
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub [1]
> 
>   *
> 
> ## Links:
> 
> [1] https://github.com/fnp/cybernauci/issues/22#issuecomment-220557664

## 

Barbara Krywoszejew
koordynatorka projektów

Fundacja Nowoczesna Polska
ul. Marszałkowska 84/92 lok. 125
00-514 Warszawa
tel./fax: +48 22 621 30 17
e-mail: fundacja@nowoczesnapolska.org.pl
www.nowoczesnapolska.org.pl

Organizacja Pożytku Publicznego
Sąd Rejestrowy dla M.St. Warszawy w Warszawie,
XII Wydział Gospodarczy
KRS 0000070056, NIP 952-18-77-087
