### ISSUE TITLE
Problem z lokowaniem grafik we wpisach w aktualnościach

### ISSUE THREAD

**Issue by paulinaoltusek** [fnp/cybernauci#24]
Nie da się ładnie ulokować tej grafiki, nie zmienia się też jej pozycja, mimo klikania w przysuwanie do prawej lub lewej krawędzie, tylko tekst dzieli się na dziwne fragmenty i wygląda to źle.

**Comment by Cain-Ish** [comment]
Brzmi jak brakujace style z wordpress. Musisz podać przykład np gdzie dokładnie dodajesz te zdjecia (jaki wpis) ale prawdopodobnie dodanie .img-left, img-right (czy jakie tam wordpress nadaje style) do style.css rozwiaze problem.
