### ISSUE TITLE
dodawanie mediów - załaczników do wpisów

### ISSUE THREAD

**Issue by kbasia** [fnp/cybernauci#27]
podczas dodawania załącznika do biblioteki multimediów pojawia się komunikat:

Nie można utworzyć katalogu &#8222;wp-content/uploads/2016/06&#8221;. Czy WordPress ma uprawnienie do zapisu do katalogu nadrzędnego?

**Comment by janek37** [comment]
Teraz powinno działać.

**Comment by kbasia** [comment]
super! dziękuję
