### ISSUE TITLE
Zmiany w zakładce O projekcie

### ISSUE THREAD

**Issue by paulinaoltusek** [fnp/cybernauci#28]
1) Zmodyfikowanie wpisu, żeby wyglądał bardziej jak podstrona, a mniej jak wpis z aktualności (usunięcie "wróć do listy", nagłówka "najnowsze informacje o programie" i "czytaj również"

2) To już dodatkowo, ale dam w jednym issuesie: Zmiana nagłówka z "Najnowsze informacje o programie" na "Najnowsze informacje o projekcie".

Dzięki! :)

**Comment by kbasia** [comment]
a czy my z poziomu admina możemy edytować treść tej storny?

**Comment by Cain-Ish** [comment]
Treść - tak jako że jest to zalinkowany post.
