### ISSUE TITLE
Wiadomość potwierdzająca rejestrację

### ISSUE THREAD

**Issue by paulinaoltusek** [fnp/cybernauci#4]
Zapomniany wcześniej mail do osób rejestrujących placówkę do udziału w projekcie.

Nadawca ?? : Fundacja Nowoczesna Polska / Cybernauci / cybernauci@nowoczesnapolska.org.pl ??
Temat: Potwierdzenie zgłoszenia placówki do udziału w projekcie
Treść: 

Dzień dobry,

Dziękujemy za przesłanie zgłoszenia do udziału w projekcie "Cybernauci - kompleksowy projekt kształtowania bezpiecznych zachowań w sieci". Niebawem skontaktujemy się z Państwem w celu przekazania szczegółów.

Z pozdrowieniami,
Zespół Fundacji Nowoczesna Polska

**Comment by kbasia** [comment]
Jako nadawcę proponuję FNP z adresem cybrenauci@

w treści zmieńmy przekazanie na ustalenie,
czyli:
Dzień dobry,

Dziękujemy za przesłanie zgłoszenia do udziału w projekcie "Cybernauci - kompleksowy projekt kształtowania bezpiecznych zachowań w sieci". Niebawem skontaktujemy się z Państwem w celu ustalenia szczegółów.

Z pozdrowieniami,
Zespół Projektu "Cybernauci"

**Comment by danielmacyszyn** [comment]
@Cain-Ish Podaj mi gdzie (w którym pliku) jest kod, który uruchamia się przy rejestracji nowej szkoły.

**Comment by Cain-Ish** [comment]
@danielmacyszyn w panelu admina pod ?page=ninja-forms&tab=notifications&form_id=6 masz 2 akcje "New school added" oraz "Registration submited". Pierwsza wysyła email do nas, druga do osoby składającej zgłoszenie (tam przy okazji mozna ustawić treści etc - hint dla @kbasia)

Aktualnie nie wysyła sie nic bo, prawdopodobnie, wordpress nie ma dostępu albo nie ma ustawionego silnika pocztowego. Tak samo jak nie ma (nie miał) dostępu do zapisywania wysyłanych obrazów w wpisach etc

**Comment by paulinaoltusek** [comment]
podbijam
