### ISSUE TITLE
Walidacja formularza zgłaszania strony

### ISSUE THREAD

**Issue by danielmacyszyn** [fnp/cybernauci#8]
Po kliknięciu "Zgłoś szkołę", w przypadku, gdy nie wszystkie pola są prawidłowo wypełnione, to następuje przekierowanie na stronę formularza, ale większość pól nie przenosi wpisanych danych i trzeba je wpisywać od nowa.

Trzeba:
- albo doprowadzić do tego, żeby wartości pół były przenoszone po przekierowaniu
- albo zrobić walidację na poziome javascriptu, tak, żeby nie trzeba było robić przekierowania i przenoszenia wartości pól (to jest chyba łatwiejsze)

Dodatkowo, po kliknięciu przycisku "Zgłoś szkołę", napis na tym przycisku zmienia się na "Processing...". Trzeba ten napis zmienić na "Przetwarzanie..."

**Comment by Cain-Ish** [comment]
@paulinaoltusek wszelkie teksty dostępne są w panelu admina pod zakładą: ?page=ninja-forms-settings&tab=label_settings - dodałem już słowa "przetwarzanie"
